#!/usr/bin/python3


r'''mrcam camera preview tool

SYNOPSIS

  $ mrcam

  [ A window pops up showing a live view of the first available camera ]

This tool provides the most basic camera tools: an image preview with some
rudimentary image capture and parameter control

'''


import sys
import argparse
import re
import os

import mrcam

def parse_args():

    parser = \
        argparse.ArgumentParser(description = __doc__,
                                formatter_class=argparse.RawDescriptionHelpFormatter)

    mrcam._add_common_cmd_options(parser,
                                  single_camera = False)

    args = parser.parse_args()

    if len(args.camera) > 1:
        print("ERROR: at this time this tool only supports one camera",
              file = sys.stderr)
        sys.exit(1)

    mrcam._parse_args_postprocess(args)

    return args


args = parse_args()

from fltk import *



kwargs = dict()
if args.dims is not None:
    kwargs['width' ] = args.dims[0]
    kwargs['height'] = args.dims[1]
if args.pixfmt is not None:
    kwargs['pixfmt'] = args.pixfmt
c = mrcam.camera(args.camera[0],
                 verbose = args.verbose,
                 recreate_stream_with_each_frame = args.recreate_stream_with_each_frame,
                 **kwargs)



W = 800
H = 600

window           = Fl_Window(W,H, "mrcam stream")
image_view_group = mrcam.Fl_Image_View_Group(0,0, W,H,
                                             camera          = c,
                                             single_buffered = args.single_buffered,
                                             feature_names   = args.features)


window.resizable(image_view_group)
window.end()
window.show()


image_view_group.set_up_image_capture(args.period)

Fl.run()
